name: Pingi pipeline

on: [push]

jobs:

  tests:
    runs-on: ubuntu-20.04
    strategy:
    max-parallel: 4
    matrix:
    python-version: [3.7]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python and Poetry
      - uses: actions/setup-python@v1
      with:
      python-version: 3.7
      - uses: Gr1N/setup-poetry@v4
        run: |
            poetry --version
            poetry install --no-interaction
      - name: Run unit tests
        run: |
            poetry run python -m unittest discover
